### ISSUE TITLE
Add Content of Strings section on playlists page

### ISSUE THREAD

**Issue by ac030540** [siesgstarena/Arena-2.0#23]
The following steps are to be followed to solve the issue:
1. Read the contribution guidelines of the project from CONTRIBUTING.md file and follow those instructions.
2. Navigate to the src->components->drawer->playlists->topicExplanationPage.
3. Create a new file named UNI03.jsx.
4. In that file, copy and paste the entire content of UNI01.jsx.
5. Add the route for UNI03.jsx in App.jsx (Refer to the route of UNI01 in App.jsx).
5. Update the gettingStartedContent, dissectingProblemContent, pseudoCodeContent and writingCodeContent in UNI03.jsx according to the data present on the page http://arena.siesgst.ac.in/playlists/topic/UNI03. 
6. Once the updates are done, you can fix all the linting issues by typing the command given in CONTRIBUTING.md.
7. Push the changes to the original repository.

**Comment by danielotieno** [comment]
@ac030540  I would love to take this.

**Comment by ac030540** [comment]
Great. Go ahead.

**Comment by danielotieno** [comment]
Wait @ac030540  has @ibokg did it?

**Comment by danielotieno** [comment]
It is always good to say you will be working on a certain issue to avoid confusion.

**Comment by ibokg** [comment]
@danielotieno I apologize

**Comment by danielotieno** [comment]
@ibokg No worries man.

**Comment by ac030540** [comment]
Resolved by @ibokg.
