### ISSUE TITLE
Add content of Adhoc, Math section on playlist page

### ISSUE THREAD

**Issue by ac030540** [siesgstarena/Arena-2.0#24]
The following steps are to be followed to solve the issue:

1. Read the contribution guidelines of the project from CONTRIBUTING.md file and follow those instructions.
2. Navigate to the src->components->drawer->playlists->topicExplanationPage.
3. Create a new file named UNI04.jsx.
4. In that file, copy and paste the entire content of UNI01.jsx.
5. Add the route for UNI04.jsx in App.jsx (Refer to the route of UNI01 in App.jsx).
6. Update the gettingStartedContent, dissectingProblemContent, pseudoCodeContent and writingCodeContent in UNI04.jsx according to the data present on the page http://arena.siesgst.ac.in/playlists/topic/UNI04.
7. Once the updates are done, you can fix all the linting issues by typing the command given in CONTRIBUTING.md.
8. Push the changes to the original repository.

**Comment by Ckpuna4** [comment]
take it

**Comment by ac030540** [comment]
Resolved!
