### ISSUE TITLE
Add content for Geometry section on playlists page

### ISSUE THREAD

**Issue by ac030540** [siesgstarena/Arena-2.0#25]
The following steps are to be followed to solve the issue:

1. Read the contribution guidelines of the project from CONTRIBUTING.md file and follow those instructions.
2. Navigate to the src->components->drawer->playlists->topicExplanationPage.
3. Create a new file named UNI05.jsx.
4. In that file, copy and paste the entire content of UNI01.jsx.
5. Add the route for UNI05.jsx in App.jsx (Refer to the route of UNI01 in App.jsx).
6. Update the gettingStartedContent, dissectingProblemContent, pseudoCodeContent and writingCodeContent in UNI05.jsx according to the data present on the page http://arena.siesgst.ac.in/playlists/topic/UNI05.
7. Once the updates are done, you can fix all the linting issues by typing the command given in CONTRIBUTING.md.
8. Push the changes to the original repository.

**Comment by poojakp94** [comment]
I would like to work on this.

**Comment by ac030540** [comment]
Great. Go ahead.

**Comment by danielotieno** [comment]
@poojakp94  are you still working on this?

**Comment by poojakp94** [comment]
@danielotieno  yes, I'm currently working on this.

**Comment by poojakp94** [comment]
@ac030540 I have submitted the pull request for this issue. Please review it.
