### ISSUE TITLE
Fixing the height issue of cards on developers route

### ISSUE THREAD

**Issue by ac030540** [siesgstarena/Arena-2.0#32]
**About the issue:**
On `/developers` route, the developer cards are not responsive. The cards have been provided a fixed height of 305px and hence on tablets, the cards look weird.

**Ideal Solution:**
The developer cards should be responsive. On tablets and mobiles, if cards are side by side and even if they don't have the same amount of content still their height should be same. It should not be the case that two side by side cards have a different heights because of different amount of content in them.

**Few things which may be helpful to solve the issue:**
1. All the components and stylesheets for `/developers` route is present in `src/Components/footerPages/developers` folder.
2. The fixed height for developer card is provided in DeveloperCard.jsx file.

**Guidelines which you should follow:**
1. Read the contributing guidelines from CONTRIBUTING.md file before working on the issue.
2. After doing all the changes, lint your code with the command given in CONTRIBUTING.md file.

**Comment by ac030540** [comment]
Hey @danielotieno, I saw your interest in contributing to our repository. Would you like to take up this issue?

**Comment by danielotieno** [comment]
@ac030540 sure

**Comment by ac030540** [comment]
The issue is open for anyone else to contribute.

**Comment by ac030540** [comment]
The issue was solved by @Mithil467
