### ISSUE TITLE
Removing "Turing Cup" from the drawer

### ISSUE THREAD

**Issue by ac030540** [siesgstarena/Arena-2.0#34]
- [ ] Remove 'Turing Cup' from the drawer. The location of the same can be viewed from the below image.
![Screenshot 2019-10-03 at 11 28 14 PM](https://user-images.githubusercontent.com/40123795/66151867-d011e680-e635-11e9-8c53-92456f4e4c26.png)

**Few things which may be helpful to solve the issue:**

1. All the components and stylesheets for the AppBar and the drawer are present in src/Components/common/AppBar folder.
2. drawerItems.js is the file which specifies the route associated with a particular drawer item.

**Guidelines which you should follow:**
1. Read the contributing guidelines from CONTRIBUTING.md file before working on the issue.
2. If you are willing to resolve the issue, add a comment on the issue stating that you are working on it.
3. After doing all the changes, lint your code with the command given in CONTRIBUTING.md file.

**Comment by drishit96** [comment]
I would like to work on this

**Comment by ac030540** [comment]
Resolved!
