### ISSUE TITLE
Improvement in Developers page

### ISSUE THREAD

**Issue by Swap76** [siesgstarena/Arena-2.0#4]
- [x] The size of card for each person should be uniform throughout the page 

- [x] Revamp the page as on our live site arena.siesgst.ac.in

**Comment by Swap76** [comment]
Add new team members and make this page as per our page on live site. @Mithil467

**Comment by Mithil467** [comment]
Okay!

**Comment by Mithil467** [comment]
I think I have done that!

**Comment by Mithil467** [comment]
Done the size part as well

**Comment by Swap76** [comment]
Great Work :-) Mithil
